### ISSUE TITLE
sample_lavels  != samples

### ISSUE THREAD

**Issue by tedgoldstein** [Kyoko-wtnb/meRedith#1]
Nice package. One thing, in the example in the README.md, the data(meRedith) imports a dataframe named **_sample_lavels_**. But the example uses the identifer **_samples_**.

You should change one or the other.  

Also, I am not sure what a **_lavel_** is.

**Comment by Kyoko-wtnb** [comment]
Thank you for your comment. The name of the data frame has been changed to samples now!!

**Comment by tedgoldstein** [comment]
Excellent

**Comment by tedgoldstein** [comment]
Dear Kyoko,
I especially like the site at http://pancancer-map.ewi.tudelft.nl/
It has many interactive features that the R package doesn’t have.  I would like to add project my mouse data using the same interface.
Where is the source code for pancancer-map.ewi.tudelft.nl ?

Thanks,
Ted

**Comment by Kyoko-wtnb** [comment]
Hi Ted, 

I did not develop the web interface so I don't have the source code, but those plots are created by R shiny using d3js features in R.
I'm asking my co-supervisor if it's possible to share the code.
I'll let you know!!

Best,
Kyoko
